apn-webapp/config/routes.rb
ApnWebapp::Application.routes.draw do
  namespace :apn do
    resources :devices
    resources :notifications
  end

  root :to => "apn/notifications#index"

end

apn-webapp/app/controllers/apn/devices_controller.rb
class Apn::DevicesController < ApplicationController
  # GET /apn/devices
  # GET /apn/devices.xml
  def index
    @apn_devices = APN::Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @apn_devices }
    end
  end

  # GET /apn/devices/1
  # GET /apn/devices/1.xml
  def show
    @apn_device = APN::Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @apn_device }
    end
  end

  # GET /apn/devices/new
  # GET /apn/devices/new.xml
  def new
    @apn_device = APN::Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @apn_device }
    end
  end

  # GET /apn/devices/1/edit
  def edit
    @apn_device = APN::Device.find(params[:id])
  end

  # POST /apn/devices
  # POST /apn/devices.xml
  def create
    @apn_device = APN::Device.new(params[:apn_device])

    respond_to do |format|
      if @apn_device.save
        format.html { redirect_to(@apn_device, :notice => 'Device was successfully created.') }
        format.xml  { render :xml => @apn_device, :status => :created, :location => @apn_device }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @apn_device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /apn/devices/1
  # PUT /apn/devices/1.xml
  def update
    @apn_device = APN::Device.find(params[:id])

    respond_to do |format|
      if @apn_device.update_attributes(params[:apn_device])
        format.html { redirect_to(@apn_device, :notice => 'Device was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @apn_device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /apn/devices/1
  # DELETE /apn/devices/1.xml
  def destroy
    @apn_device = APN::Device.find(params[:id])
    @apn_device.destroy

    respond_to do |format|
      format.html { redirect_to(apn_devices_url) }
      format.xml  { head :ok }
    end
  end
end

apn-webapp/app/controllers/apn/notifications_controller.rb
class Apn::NotificationsController < ApplicationController
  # GET /apn/notifications
  # GET /apn/notifications.xml
  def index
    @apn_notifications = APN::Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @apn_notifications }
    end
  end

  # GET /apn/notifications/1
  # GET /apn/notifications/1.xml
  def show
    @apn_notification = APN::Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @apn_notification }
    end
  end

  # GET /apn/notifications/new
  # GET /apn/notifications/new.xml
  def new
    @apn_notification = APN::Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @apn_notification }
    end
  end

  # GET /apn/notifications/1/edit
  def edit
    @apn_notification = APN::Notification.find(params[:id])
  end

  # POST /apn/notifications
  # POST /apn/notifications.xml
  def create
    @apn_notification = APN::Notification.new(params[:apn_notification])

    respond_to do |format|
      if @apn_notification.save
        format.html { redirect_to(@apn_notification, :notice => 'Notification was successfully created.') }
        format.xml  { render :xml => @apn_notification, :status => :created, :location => @apn_notification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @apn_notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /apn/notifications/1
  # PUT /apn/notifications/1.xml
  def update
    @apn_notification = APN::Notification.find(params[:id])

    respond_to do |format|
      if @apn_notification.update_attributes(params[:apn_notification])
        format.html { redirect_to(@apn_notification, :notice => 'Notification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @apn_notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /apn/notifications/1
  # DELETE /apn/notifications/1.xml
  def destroy
    @apn_notification = APN::Notification.find(params[:id])
    @apn_notification.destroy

    respond_to do |format|
      format.html { redirect_to(apn_notifications_url) }
      format.xml  { head :ok }
    end
  end
end

apn-webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

apn-webapp/app/helpers/apn/devices_helper.rb
module Apn::DevicesHelper
end

apn-webapp/app/helpers/apn/notifications_helper.rb
module Apn::NotificationsHelper
end

apn-webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

apn-webapp/app/views/apn/devices/_form.html.erb
<%= form_for(@apn_device) do |f| %>
  <% if @apn_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apn_device.errors.count, "error") %> prohibited this apn_device from being saved:</h2>

      <ul>
      <% @apn_device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :token %>
    <div class="input">
      <%= f.text_field :token, :class => "xxlarge" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn primary" %>
    <% unless @apn_device.new_record? %><%= link_to 'Show', @apn_device, class: "btn info" %><% end %>
    <%= link_to 'Back', apn_devices_path %>
  </div>
<% end %>

apn-webapp/app/views/apn/devices/edit.html.erb
<div class="page-header">
  <h1>Editing apn_device</h1>
</div>

<%= render 'form' %>

apn-webapp/app/views/apn/devices/index.html.erb
<div class="page-header">
  <h1>Listing apn_devices</h1>
</div>

<table>
  <tr>
    <th>Token</th>
    <th></th>
  </tr>

<% @apn_devices.each do |apn_device| %>
  <tr>
    <td><%= link_to apn_device.token, apn_device %></td>
    <td>
      <%= link_to 'Show', apn_device, class: "btn info" %>
      <%= link_to 'Edit', edit_apn_device_path(apn_device), class: :btn %>
      <%= link_to 'Destroy', apn_device, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_apn_device_path, class: "btn large primary" %>

apn-webapp/app/views/apn/devices/new.html.erb
<div class="page-header">
  <h1>New apn_device</h1>
</div>

<%= render 'form' %>

apn-webapp/app/views/apn/devices/show.html.erb
<% if notice %><div class="alert-message success"><p><%= notice %></p></div><% end %>

<p>
  <b>Token:</b>
  <%= @apn_device.token %>
</p>

<p>
  <b>Created at:</b>
  <%= @apn_device.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @apn_device.updated_at %>
</p>

<%= link_to 'Edit', edit_apn_device_path(@apn_device), class: :btn %>
<%= link_to 'Back', apn_devices_path %>

apn-webapp/app/views/apn/notifications/_form.html.erb
<%= form_for(@apn_notification) do |f| %>
  <% if @apn_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apn_notification.errors.count, "error") %> prohibited this apn_notification from being saved:</h2>

      <ul>
      <% @apn_notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :device_id %>
    <div class="input">
      <%= f.collection_select(:device_id, APN::Device.all, :id, :token) %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :sound %>
    <div class="input">
      <%= f.text_field :sound %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :alert %>
    <div class="input">
      <%= f.text_field :alert %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :badge %>
    <div class="input">
      <%= f.text_field :badge %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn primary" %>
    <% unless @apn_notification.new_record? %><%= link_to 'Show', @apn_notification, class: "btn info" %><% end %>
    <%= link_to 'Back', apn_notifications_path %>
  </div>
<% end %>

apn-webapp/app/views/apn/notifications/edit.html.erb
<div class="page-header">
  <h1>Editing apn_notification</h1>
</div>

<%= render 'form' %>

apn-webapp/app/views/apn/notifications/index.html.erb
<div class="page-header">
  <h1>Listing apn_notifications</h1>
</div>

<table>
  <tr>
    <th>Alert</th>
    <th>Sent at</th>
    <th></th>
  </tr>

<% @apn_notifications.each do |apn_notification| %>
  <tr>
    <td>
      <%= apn_notification.alert %> <% if apn_notification.badge %><span class="label important"><%= apn_notification.badge %></span><% end %><br/>
      <%= link_to apn_notification.device.token, apn_notification.device %>
    </td>
    <td><%= apn_notification.sent_at %></td>
    <td>
      <%= link_to 'Show', apn_notification, {class: "btn info"} %>
      <%= link_to 'Edit', edit_apn_notification_path(apn_notification), {class: :btn} %>
      <%= link_to 'Destroy', apn_notification, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_apn_notification_path, class: "btn large primary" %>

apn-webapp/app/views/apn/notifications/new.html.erb
<div class="page-header">
  <h1>New apn_notification</h1>
</div>

<%= render 'form' %>

apn-webapp/app/views/apn/notifications/show.html.erb
<% if notice %><div class="alert-message success"><p><%= notice %></p></div><% end %>

<p>
  <b>Device:</b>
  <%= link_to @apn_notification.device.token, @apn_notification.device %>
</p>

<p>
  <b>Errors nb:</b>
  <%= @apn_notification.errors_nb %>
</p>

<p>
  <b>Device language:</b>
  <%= @apn_notification.device_language %>
</p>

<p>
  <b>Sound:</b>
  <%= @apn_notification.sound %>
</p>

<p>
  <b>Alert:</b>
  <%= @apn_notification.alert %>
</p>

<p>
  <b>Badge:</b>
  <%= @apn_notification.badge %>
</p>

<p>
  <b>Custom properties:</b>
  <%= @apn_notification.custom_properties %>
</p>

<p>
  <b>Sent at:</b>
  <%= @apn_notification.sent_at %>
</p>

<p>
  <b>Created at:</b>
  <%= @apn_notification.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @apn_notification.updated_at %>
</p>


<%= link_to 'Edit', edit_apn_notification_path(@apn_notification), class: :btn %>
<%= link_to 'Back', apn_notifications_path %>

apn-webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApnWebapp</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<div class="container">
  <div class="content">
<%= yield %>
  </div>
</div>

<%= javascript_include_tag :defaults %>
</body>
</html>